import Link from "next/link";
import { withBasePath } from "@/lib/paths";
import { RotatingQuote } from "@/components/home-carousel";
import { products as productPages } from "@/lib/products";
import type { Metadata } from "next";

export const metadata: Metadata = { alternates: { canonical: "/" }, openGraph: { title: "SQL Optima | Monitor. Compare. Recover.", description: "Database tools and operational guides for SQL Server and PostgreSQL.", images: [{ url: "/images/home/hero-banner-v2.png", alt: "SQL Optima database tooling" }] } };

type IconName = "activity" | "compare" | "migration" | "assessment" | "backup" | "book" | "network";
const productPresentation: Record<string, { icon: IconName; tone: string }> = { "sql-monitoring": { icon: "activity", tone: "sky" }, "schema-compare": { icon: "compare", tone: "violet" }, "migration-toolkit": { icon: "migration", tone: "amber" }, "assessment-generator": { icon: "assessment", tone: "teal" }, "backup-manager": { icon: "backup", tone: "green" }, "dba-handbook": { icon: "book", tone: "indigo" }, "ha-cluster-lab": { icon: "network", tone: "rose" } };
const practiceAreas = [
  ["development", "Development", "Database design, queries, stored procedures, and the path between the application and SQL Server or PostgreSQL. Schema compare shows drift before a release ships the wrong objects."],
  ["administration", "Administration", "The daily work of keeping both engines tidy: jobs, space, backups you can restore, and a server that behaves the same tomorrow. Monitoring shows what changed overnight."],
  ["security", "Security", "Who can see what, audits, and keeping sensitive data in the place you intended. Reviews cover logins, permissions, and the paths data should never take."],
  ["availability", "High availability and disaster recovery", "Fewer outages, a failover you have rehearsed, and a way back when the site is down. Practice the cutover in the HA lab before the night you need it."],
  ["performance", "Optimization and performance", "Find the slow query, the bad plan, or the resource that is full, then fix that instead of buying a bigger server first. An assessment points at the wait that actually matters."],
  ["training", "Training and workshops", "Classes where you practice on SQL Server and PostgreSQL, not only watch slides. Workshops follow the work itself: design, run, protect, recover, and tune."],
  ["consulting", "Consulting", "Help shaped to your architecture, performance, security, availability, and how the team actually works. The tools stay with you; we join the work when you want another pair of hands."],
  ["ai-sql-mcp", "AI and SQL MCP", "AI and SQL MCP so someone can ask the database a question and get an answer that knows the schema. The reply uses the objects you already have, not a generic guess."],
] as const;
const engines = [["SQL Server", "/images/engines/sql-server.svg", "Core tools and guidance"], ["PostgreSQL", "/images/engines/postgresql.svg", "Monitoring, migration, labs, and guidance"]] as const;
const services = [["Performance Tuning", "Bring the slow window, Query Store or pg_stat_statements history, and plans; leave with the bottleneck, tested change, and before/after evidence."], ["Database Health Check", "Review configuration, waits, storage, backups, security, and HA evidence, then turn findings into an owned remediation queue."], ["Migration Support", "Assess SQL Server-to-PostgreSQL blockers, rehearse data movement and validation, and document cutover and rollback decisions."], ["Architecture Review", "Test the proposed topology against workload, failure domains, recovery objectives, capacity, and the team that must operate it."], ["DBA Support", "Add experienced review during incidents, risky changes, capacity decisions, or periods when the internal team needs another pair of hands."], ["SQL Training", "Practice query tuning, backup and restore, HA, migration, and production diagnosis in labs tied to reusable scripts and checklists."]] as const;
const tasks = [
  ["Find a performance problem", "Trace waits and expensive queries to the workload behind them.", "/products/sql-monitoring/"],
  ["Compare database schemas", "Review drift and generate ordered SQL Server deployment scripts.", "/products/schema-compare/"],
  ["Plan a PostgreSQL migration", "Assess, convert, move, validate, and rehearse cutover.", "/products/migration-toolkit/"],
  ["Assess SQL Server health", "Collect repeatable evidence and produce a structured report.", "/products/assessment-generator/"],
  ["Improve backup and recovery", "Operate verified backup chains and durable retention.", "/products/backup-manager/"],
  ["Practice failover", "Run database traffic through controlled HA lab scenarios.", "/products/ha-cluster-lab/"],
] as const;
const personas = [
  ["DBA", "Triage waits, blocking, backup state, capacity, and configuration before the next incident.", "/products/sql-monitoring/"],
  ["Developer", "Review schema drift and query behavior before a database change reaches production.", "/products/schema-compare/"],
  ["Platform team", "Run monitoring and recovery tooling inside infrastructure your team controls.", "/products/sql-monitoring/"],
  ["Engineering lead", "Turn assessment evidence into a prioritized, reviewable remediation plan.", "/products/assessment-generator/"],
  ["Migration team", "Assess conversion work, move data, validate results, and rehearse cutover.", "/products/migration-toolkit/"],
] as const;

export default function Home() {
  return <main className="home-canvas">
    <section className="stable-hero" aria-labelledby="home-title"><img src={withBasePath("/images/home/hero-banner-v2.png")} alt="" /><div className="source-hero-scrim" /><div className="page-wrap stable-hero-copy"><p className="source-pill">SQL Server and PostgreSQL</p><h1 id="home-title">Monitor. Compare. Recover.</h1><p>Practical database tools for DBAs and engineering teams who need to find performance problems, review schema changes, move workloads, and rehearse recovery.</p><div className="hero-badges" aria-label="Product characteristics"><span>Self-hosted tools</span><span>Database-aware</span><span>Operational guides</span></div><div className="source-actions"><a className="primary-action" href="#products">Explore tools</a><a className="outline-action hero-outline" href="https://github.com/rsharma155" target="_blank" rel="noreferrer">View on GitHub</a></div></div></section>
    <section className="page-wrap source-intro"><p className="source-lead">Use the software directly, learn from the handbook and field guides, or bring in professional help for an assessment, migration, workshop, or difficult production problem.</p><RotatingQuote /></section>
    <section className="page-wrap source-section task-section" aria-labelledby="task-title"><h2 id="task-title">What are you trying to do?</h2><p>Start with the database problem, not the product catalog.</p><div className="task-grid">{tasks.map(([title, summary, href]) => <Link href={href} key={title}><strong>{title}</strong><span>{summary}</span><b>Start here →</b></Link>)}</div></section>
    <section className="page-wrap source-section" id="products" aria-labelledby="products-title"><h2 id="products-title">Products</h2><p>Tools for monitoring, change, migration, assessment, backup, and high-availability practice.</p><div className="source-product-grid">{productPages.filter((product) => product.slug !== "dba-handbook").map((product) => { const presentation = productPresentation[product.slug]; return <article className="source-product-card" key={product.title}><Link className="product-image-link" href={`/products/${product.slug}/`}><img className="product-card-image" src={withBasePath(product.image)} alt={`${product.title} ${product.imageKind}`} /></Link><div className="product-card-body"><span className={`product-icon ${presentation.tone}`}><ProductIcon name={presentation.icon} /></span><div className="product-text"><strong>{product.title}</strong><p>{product.outcome}</p><span className="product-proof">{product.engineSupport.map(({ engine, level }) => `${engine}: ${level}`).join(" · ")} · {product.maturity}</span><span className="product-card-actions"><Link href={`/products/${product.slug}/`}>Explore</Link><a href={product.repository} target="_blank" rel="noreferrer">Repository ↗</a></span></div></div></article>; })}</div></section>
    <section className="page-wrap source-section showcase-section" aria-labelledby="showcase-title"><hr /><h2 id="showcase-title">See SQL Optima in action</h2><p>Three common jobs, using current screenshots where repositories provide them and clearly labeled illustrations elsewhere.</p><div className="product-showcase">{productPages.filter((product) => ["sql-monitoring", "schema-compare", "migration-toolkit"].includes(product.slug)).map((product, index) => <article key={product.slug} className={index % 2 ? "showcase-reverse" : ""}><figure><img src={withBasePath(product.image)} alt={`${product.title} ${product.imageKind}`} /><figcaption><strong>{product.imageKind === "screenshot" ? "Product screenshot" : "Illustration"}</strong>{product.imageCaption}</figcaption></figure><div><p className="eyebrow">{product.engineSupport.map(({ engine, level }) => `${engine} ${level.toLowerCase()}`).join(" · ")}</p><h3>{product.title}</h3><p>{product.introduction}</p><ul>{product.highlights.map((highlight) => <li key={highlight}>{highlight}</li>)}</ul><Link href={`/products/${product.slug}/`}>Explore {product.title} →</Link></div></article>)}</div></section>
    <section className="page-wrap source-section workflow-section" aria-labelledby="workflow-title"><hr /><h2 id="workflow-title">From signal to action</h2><ol className="home-workflow"><li><WorkflowIcon name="observe" /><strong>Observe</strong><span>See waits, workload, backup state, and operational signals.</span></li><li><WorkflowIcon name="diagnose" /><strong>Diagnose</strong><span>Connect the symptom to a query, configuration, or schema change.</span></li><li><WorkflowIcon name="act" /><strong>Act</strong><span>Review the proposed change, migration, or recovery step.</span></li><li><WorkflowIcon name="verify" /><strong>Verify</strong><span>Compare the result with the baseline and keep the evidence.</span></li></ol></section>
    <section className="page-wrap source-section ecosystem-section" aria-labelledby="ecosystem-title"><hr /><h2 id="ecosystem-title">One operating loop across the toolkit</h2><p>Observe the live system, change it with review, and keep a tested recovery path.</p><div className="ecosystem-diagram"><div><span>01</span><strong>Observe</strong><small>Monitoring and assessment expose waits, workload, capacity, and configuration.</small><b>SQL Monitoring · Assessment Collector</b></div><i aria-hidden>→</i><div><span>02</span><strong>Change</strong><small>Compare schemas or migrate data with explicit review and validation steps.</small><b>Schema Compare · Migration Toolkit</b></div><i aria-hidden>→</i><div><span>03</span><strong>Recover</strong><small>Verify backup chains and rehearse failures before the production event.</small><b>Backup Manager · HA Cluster Lab</b></div></div><p className="diagram-note">The same evidence loop applies throughout: capture a baseline, make one controlled change, and verify the result.</p></section>
    <section className="page-wrap source-section knowledge-section" id="knowledge" aria-labelledby="knowledge-title"><hr /><h2 id="knowledge-title">Knowledge</h2><p>Checklists, scripts, explanations, and operational playbooks you can use at the keyboard.</p><div className="knowledge-links"><Link href="/handbook/"><strong>DBA Handbook</strong><span>Repeatable operational guidance and checklists.</span></Link><Link href="/blog/"><strong>Field guides</strong><span>Focused SQL Server and PostgreSQL investigations.</span></Link><Link href="/docs/"><strong>All technical guides</strong><span>Browse documentation, handbooks, articles, labs, and interactive resources together.</span></Link></div></section>
    <section className="page-wrap source-practice" aria-labelledby="practice-title"><hr /><h2 id="practice-title">For people who live in SQL Server and PostgreSQL</h2><div className="practice-copy"><p>A lot of the day is ordinary: a query that got slow, a login that should not be there, a failover nobody has tried. The free tools cover much of that. Training and consulting are for the parts you want to learn, or hand to someone who has done them before.</p><p>The same skills show up on both engines. Design, administration, security, high availability, disaster recovery, and performance. Workshops are hands-on. Consulting follows your architecture and how you operate. We also work with AI and SQL MCP when you want the database to answer with the schema in mind.</p></div><div className="skill-icons" aria-label="Design, administration, security, high availability, disaster recovery, and performance">{["✎","▰","◇","⌁","↻","⌁"].map((icon,index)=><span key={`${icon}-${index}`}>{icon}</span>)}</div><div className="practice-area-grid">{practiceAreas.map(([id,title,summary]) => <Link href={`/practice/${id}/`} className="practice-area-card" key={id}><img src={withBasePath(`/images/practice/icons/${id === "ai-sql-mcp" ? "ai" : id}-ui.png`)} alt="" /><span><strong>{title}</strong><small>{summary}</small></span></Link>)}</div><p className="practice-close">The tools stay free, so you can use them on the everyday jobs. Training and consulting are there when you want a class or a second opinion.</p></section>
    <section className="page-wrap source-section engine-source" aria-labelledby="engine-title"><hr /><h2 id="engine-title">Current platform focus</h2><p>Coverage varies by product; each product page states its own scope.</p><div className="source-engine-grid core-engines">{engines.map(([name,src,scope])=><div className="source-engine" key={name}><img src={withBasePath(src)} alt="" /><strong>{name}</strong><small>{scope}</small></div>)}</div><p className="scope-note">Oracle and MySQL are not presented as having equivalent toolkit coverage.</p></section>
    <section className="page-wrap source-section matrix-section" aria-labelledby="matrix-title"><h2 id="matrix-title">Capability and engine support</h2><p>Specific roles such as migration source, target, guidance, and lab are shown instead of a vague checkmark.</p><div className="support-table-wrap"><table className="support-table"><thead><tr><th scope="col">Product</th><th scope="col">SQL Server</th><th scope="col">PostgreSQL</th><th scope="col">Status</th></tr></thead><tbody>{productPages.map((product) => <tr key={product.slug}><th scope="row"><Link href={`/products/${product.slug}/`}>{product.title}</Link></th>{(["SQL Server", "PostgreSQL"] as const).map((engine) => <td key={engine}>{product.engineSupport.find((support) => support.engine === engine)?.level ?? "Not listed"}</td>)}<td>{product.maturity}</td></tr>)}</tbody></table></div><p className="scope-note">Scope reviewed {productPages[0].verifiedAt}. Follow each product’s repository for current installation and release details.</p></section>
    <section className="page-wrap source-section persona-section" aria-labelledby="persona-title"><hr /><h2 id="persona-title">Choose a path for your role</h2><p>Start with the decision you own, then move into the relevant product or guide.</p><div className="persona-grid">{personas.map(([role, summary, href]) => <Link href={href} key={role}><span>{role}</span><p>{summary}</p><b>Open role path →</b></Link>)}</div></section>
    <section className="page-wrap source-section why-section" aria-labelledby="why-title"><hr /><div className="why-grid"><div><p className="eyebrow">Why SQL Optima</p><h2 id="why-title">Built around the database work, not a generic dashboard.</h2></div><div><p>SQL Optima is an independent database-tooling project created and maintained by Ravi Sharma. The tools and practical guides can be used directly. Consulting and training are separate options for teams that want help applying them to a real estate.</p><ul><li><strong>Database-aware:</strong> workflows begin with waits, plans, schema drift, backup chains, and cutover evidence.</li><li><strong>Self-hosted where stated:</strong> deployment mode is listed per product rather than implied across the suite.</li><li><strong>Evidence before claims:</strong> support status and project links come from the same product metadata used across the site.</li></ul><Link href="/about/">About the maintainer →</Link></div></div></section>
    <section className="page-wrap source-section services-source" id="professional-help" aria-labelledby="services-title"><hr /><h2 id="services-title">Professional help</h2><p>Independent consulting and training are available when your team wants hands-on help alongside the tools.</p><div className="source-services-grid">{services.map(([title,summary])=><a href="mailto:ravisharma155@gmail.com" className="source-service" key={title}><span className="service-icon" aria-hidden>⌁</span><span><strong>{title}</strong><small>{summary}</small></span></a>)}</div></section>
  </main>;
}

function ProductIcon({ name }: { name: IconName }) {
  const paths: Record<IconName, React.ReactNode> = { activity: <path d="M3 12h4l2-7 4 14 2-7h6" />, compare: <><path d="M8 3 4 7l4 4"/><path d="M4 7h13"/><path d="m16 13 4 4-4 4"/><path d="M20 17H7"/></>, migration: <><path d="M7 7h11l-3-3"/><path d="m18 7-3 3"/><path d="M17 17H6l3 3"/><path d="m6 17 3-3"/></>, assessment: <><path d="M9 5h6"/><rect x="5" y="3" width="14" height="18" rx="2"/><path d="m8 13 2 2 5-5"/></>, backup: <><path d="M4 4h16v6H4z"/><path d="M4 14h16v6H4z"/><path d="M16 7h.01M16 17h.01"/></>, book: <><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"/></>, network: <><rect x="9" y="2" width="6" height="6" rx="1"/><rect x="3" y="16" width="6" height="6" rx="1"/><rect x="15" y="16" width="6" height="6" rx="1"/><path d="M12 8v4M6 16v-4h12v4"/></> };
  return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden>{paths[name]}</svg>;
}

function WorkflowIcon({ name }: { name: "observe" | "diagnose" | "act" | "verify" }) {
  const paths = { observe: <><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></>, diagnose: <><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4M11 8v3l2 2"/></>, act: <><path d="m14.7 6.3 3 3M3 21l3.7-1 11-11a2.1 2.1 0 0 0-3-3l-11 11L3 21Z"/><path d="m12 20 9-9"/></>, verify: <><path d="M20 6 9 17l-5-5"/><path d="M21 12a9 9 0 1 1-5-8.2"/></> };
  return <span className={`workflow-icon workflow-${name}`} aria-hidden><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg></span>;
}
