import Link from "next/link";
import { withBasePath } from "@/lib/paths";
import { HomeCarousel, RotatingQuote } from "@/components/home-carousel";

type IconName = "activity" | "compare" | "migration" | "assessment" | "backup" | "book" | "network";
const products: ReadonlyArray<{ title: string; description: string; repo: string; icon: IconName; tone: string; preview: string }> = [
  { title: "SQL Monitoring", description: "Health and performance telemetry, rule-based checks, and query triage for SQL Server and PostgreSQL.", repo: "https://github.com/rsharma155/sql_optima", icon: "activity", tone: "sky", preview: "/images/monitoring/sqlserver-dashboard.png" },
  { title: "Schema Compare", description: "Windows GUI and cross-platform CLI to diff procedures, indexes, and tables across environments.", repo: "https://github.com/rsharma155/sqloptima_compare", icon: "compare", tone: "violet", preview: "/images/products/sql-optima-schema-compare-hero.png" },
  { title: "Migration Toolkit", description: "SQL Server to PostgreSQL cutovers with stored-procedure and function conversion.", repo: "https://github.com/rsharma155/sqloptima_migration", icon: "migration", tone: "amber", preview: "/images/products/sql-optima-migration-hero.png" },
  { title: "Assessment Generator", description: "Automated SQL Server and Postgres audits that produce HTML and PDF health reports.", repo: "https://github.com/rsharma155/dba_handbook", icon: "assessment", tone: "teal", preview: "/images/products/dba-handbook-hero.png" },
  { title: "Backup Manager", description: "Windows SQL Server backup platform with a control panel and a web operations console.", repo: "https://github.com/rsharma155/sqloptima_backup", icon: "backup", tone: "green", preview: "/images/products/sqloptima-backup-pro-hero.png" },
  { title: "DBA Handbook", description: "Searchable operational guidance for SQL Server, PostgreSQL, and more.", repo: "https://github.com/rsharma155/dba_handbook", icon: "book", tone: "indigo", preview: "/images/products/dba-handbook-hero.png" },
  { title: "HA Cluster Lab", description: "Side-by-side Patroni PostgreSQL and SQL Server clusters with failover traffic generation.", repo: "https://github.com/rsharma155/sqlserver_postgres_ha_cluster", icon: "network", tone: "rose", preview: "/images/monitoring/postgres-dashboard.png" },
];
const practiceAreas = [
  ["development", "Development", "Database design, queries, stored procedures, and the path between the application and SQL Server or PostgreSQL. Schema compare shows drift before a release ships the wrong objects."],
  ["administration", "Administration", "The daily work of keeping both engines tidy: jobs, space, backups you can restore, and a server that behaves the same tomorrow. Monitoring shows what changed overnight."],
  ["security", "Security", "Who can see what, audits, and keeping sensitive data in the place you intended. Reviews cover logins, permissions, and the paths data should never take."],
  ["availability", "High availability and disaster recovery", "Fewer outages, a failover you have rehearsed, and a way back when the site is down. Practice the cutover in the HA lab before the night you need it."],
  ["performance", "Optimization and performance", "Find the slow query, the bad plan, or the resource that is full, then fix that instead of buying a bigger server first. An assessment points at the wait that actually matters."],
  ["training", "Training and workshops", "Classes where you practice on SQL Server and PostgreSQL, not only watch slides. Workshops follow the work itself: design, run, protect, recover, and tune."],
  ["consulting", "Consulting", "Help shaped to your architecture, performance, security, availability, and how the team actually works. The tools stay with you; we join the work when you want another pair of hands."],
  ["ai", "AI and SQL MCP", "AI and SQL MCP so someone can ask the database a question and get an answer that knows the schema. The reply uses the objects you already have, not a generic guess."],
] as const;
const engines = [["SQL Server", "/images/engines/sql-server.svg"], ["PostgreSQL", "/images/engines/postgresql.svg"], ["Oracle", "/images/engines/oracle.svg"], ["MySQL", "/images/engines/mysql.svg"]] as const;
const services = [["Performance Tuning", "Query plans, indexing, and workload triage by seasoned DBAs."], ["Database Health Check", "Configuration, HA, and reliability review with a clear remediation plan."], ["Cloud Migration", "Move platforms without guessing cutover risk."], ["Architecture Review", "HA topology, capacity, and operational maturity with prioritized remediations."], ["DBA Support", "Retainer-style coverage for production incidents and continuous improvement."], ["SQL Training", "Team workshops on query tuning, indexing, and platform operations."]] as const;

export default function Home() {
  return <main className="home-canvas">
    <HomeCarousel />
    <section className="page-wrap source-intro"><div className="source-actions"><a className="primary-action" href="https://github.com/rsharma155" target="_blank" rel="noreferrer">Open GitHub projects</a><Link className="outline-action" href="/handbook/">Read the handbook</Link></div><p className="source-lead">sqloptima is free SQL Server and PostgreSQL tools, plus training, workshops, and consulting when you want someone in the work with you. We help teams build, run, secure, and speed up the databases they already have.</p><RotatingQuote /></section>
    <section className="page-wrap source-section" id="products" aria-labelledby="products-title"><h2 id="products-title">Products</h2><p>Software-first tooling for DBAs — monitoring through HA lab.</p><div className="source-product-grid">{products.map((product) => <a href={product.repo} target="_blank" rel="noreferrer" className="source-product-card" key={product.title}><img className="product-card-image" src={withBasePath(product.preview)} alt={`${product.title} interface`} /><span className="product-card-body"><span className={`product-icon ${product.tone}`}><ProductIcon name={product.icon} /></span><span className="product-text"><strong>{product.title}</strong><small>{product.description}</small></span></span></a>)}</div></section>
    <section className="page-wrap source-practice" aria-labelledby="practice-title"><hr /><h2 id="practice-title">For people who live in SQL Server and PostgreSQL</h2><div className="practice-copy"><p>A lot of the day is ordinary: a query that got slow, a login that should not be there, a failover nobody has tried. The free tools cover much of that. Training and consulting are for the parts you want to learn, or hand to someone who has done them before.</p><p>The same skills show up on both engines. Design, administration, security, high availability, disaster recovery, and performance. Workshops are hands-on. Consulting follows your architecture and how you operate. We also work with AI and SQL MCP when you want the database to answer with the schema in mind.</p></div><div className="skill-icons" aria-label="Design, administration, security, high availability, disaster recovery, and performance">{["✎","▰","◇","⌁","↻","⌁"].map((icon,index)=><span key={`${icon}-${index}`}>{icon}</span>)}</div><div className="practice-area-grid">{practiceAreas.map(([id,title,summary]) => <Link href="/practice/" className="practice-area-card" key={id}><img src={withBasePath(`/images/practice/icons/${id}-ui.png`)} alt="" /><span><strong>{title}</strong><small>{summary}</small></span></Link>)}</div><p className="practice-close">The tools stay free, so you can use them on the everyday jobs. Training and consulting are there when you want a class or a second opinion.</p></section>
    <section className="page-wrap source-section engine-source" id="solutions" aria-labelledby="engine-title"><hr /><h2 id="engine-title">Solutions by engine</h2><div className="source-engine-grid">{engines.map(([name,src])=><div className="source-engine" key={name}><img src={withBasePath(src)} alt="" /><strong>{name}</strong></div>)}</div></section>
    <section className="page-wrap source-section services-source" id="services" aria-labelledby="services-title"><hr /><h2 id="services-title">Premium Services</h2><p>Consulting wraps the platform — not the other way around.</p><div className="source-services-grid">{services.map(([title,summary])=><a href="mailto:hello@sqloptima.net" className="source-service" key={title}><span className="service-icon" aria-hidden>⌁</span><span><strong>{title}</strong><small>{summary}</small></span></a>)}</div></section>
  </main>;
}

function ProductIcon({ name }: { name: IconName }) {
  const paths: Record<IconName, React.ReactNode> = { activity: <path d="M3 12h4l2-7 4 14 2-7h6" />, compare: <><path d="M8 3 4 7l4 4"/><path d="M4 7h13"/><path d="m16 13 4 4-4 4"/><path d="M20 17H7"/></>, migration: <><path d="M7 7h11l-3-3"/><path d="m18 7-3 3"/><path d="M17 17H6l3 3"/><path d="m6 17 3-3"/></>, assessment: <><path d="M9 5h6"/><rect x="5" y="3" width="14" height="18" rx="2"/><path d="m8 13 2 2 5-5"/></>, backup: <><path d="M4 4h16v6H4z"/><path d="M4 14h16v6H4z"/><path d="M16 7h.01M16 17h.01"/></>, book: <><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"/></>, network: <><rect x="9" y="2" width="6" height="6" rx="1"/><rect x="3" y="16" width="6" height="6" rx="1"/><rect x="15" y="16" width="6" height="6" rx="1"/><path d="M12 8v4M6 16v-4h12v4"/></> };
  return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden>{paths[name]}</svg>;
}
